### ISSUE TITLE
Dropdown nav menu do not work any more, since Boostrap 3 need jQuery 2, and Dokuwiki update to jQurey 3

### ISSUE THREAD

**Issue by Lukas238** [LotarProject/dokuwiki-plugin-bootswrapper#64]
Dropdown nav menu in Bootstrap menu no longer works since DokuWiki last version use jQuery version 3, and Bootstrap.js need jQuery version 2.

**Comment by werdlerk** [comment]
Indeed, we're stuck now on Dokuwiki version 2016-06-26a "Elenor of Tsort" due to this defect.

Anybody know how to fix this in Bootstrap? Does Bootstrap in bootswrapper need to be updated so it can work with JQuery 3?
Has anybody already fixed this, maybe in a [fork](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/network)?

**Comment by LotarProject** [comment]
Hi! This plugin generally use the Bootstrap js bundled in Bootstrap3 template. The latest version of Bootstrap (bundled in Bootstrap3 template) include the support for jQuery 3.x (http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/).

I suggest to:

- update the template to latest version
- fix DokuWiki permission (specially for the new jQuery dispatcher `<dokuwiki>/lib/exe.jquery.php` introduced in the latest DokuWiki release)
- purge the JS and CSS cache (via ``http://<dokuwiki>/lib/exe/js.php?purge=true`` and ``http://<dokuwiki>/lib/exe/css.php?purge=true``)
- touch the DokuWiki configuration file to purge all caches
- flush browser cache (specially for Chrome/Chromium)

At your disposal,
Joseph

**Comment by LotarProject** [comment]
LotarProject/dokuwiki-template-bootstrap3#291
