### ISSUE TITLE
Callouts icons not showing

### ISSUE THREAD

**Issue by joanalexisc** [LotarProject/dokuwiki-plugin-bootswrapper#80]
Hi, Im trying to use the callout component but the icon is not showing when I set the icon property to true.
It just leave the white space for the icon.

**Comment by MvErven** [comment]
You must not set the icon="true" 
You have to tell what icon to use.

`<callout type="danger" icon="fa fa-tint">
It's possible to change the theme (skin) of this wiki to enhance readability. Please feel free to change this theme according to your preference. 
</callout>`

**Comment by LotarProject** [comment]
@joanalexisc you can paste the snippet of your callout ?

**Comment by joanalexisc** [comment]
hi, Im just trying to use the defaults callouts, but the icon is not showing anyway. Im using the default theme. If you like you can see the result here: http://husky-wiki.com/test

The snippet of my callout is:
<callout icon="fa fa-user" color="yellow"> [...] </callout>

<callout type="primary" title="JEJE" icon="true"> Prueba </callout>
<callout type="success" icon="true"> [...] </callout>
<callout type="info" icon="true"> [...] </callout>
<callout type="warning" icon="true"> [...] </callout>
<callout type="danger" icon="true"> [...] </callout>

**Comment by LotarProject** [comment]
Hi @joanalexisc ,
the problem is the default DokuWiki template. Bootstrap Wrapper plugin require a Bootstrap-based template (eg. my Bootstrap3 template - https://www.dokuwiki.org/template:bootstrap3) and FontAwesome icons (bundled into Bootstrap3 template).

If do you want to use the default DokuWiki theme and only the callout syntax i suggest to install my **icons** plugin (http://dokuwiki.org/plugin:icons) and activate FontAwesome from CDN url via Configuration Manager (`loadFontAwesome` config).

At your disposal,
Joseph

**Comment by joanalexisc** [comment]
it works, but now I see that your plugin change the Configuration Manager font to something unreadable(smaller font size and color to white).
By the way Your Bootstrap3 template looks good but I saw some issues in a quick change that I did on my site. will try it later.

**Comment by MvErven** [comment]
@joanalexisc  Well, had a look at the site. Looks promissing!  May I suggest using the translate plugin for an English version? (page translation from Chrome isn't great) Keep up the good work. Cheers!
